<?php

namespace Database\Seeders;

use App\Models\Component;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ComponentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $components = [
            ['code' => 'ADU', 'description' => 'Air duct'],
            ['code'=> 'ARD', 'description' => 'Anti-rack device'],
            ['code' => 'CFG', 'description' => 'Corner fitting'],
            ['code' => 'CMA', 'description' => 'Cross-member assembly'],
            ['code' => 'CMF', 'description' => 'Cross-member fixing plate/T-clip'],
            ['code' => 'CML', 'description' => 'Cross-member lower flange'],
            ['code' => 'CMO', 'description' => 'Outrigger'],
            ['code' => 'CMU', 'description' => 'Cross-member upper flange'],
            ['code' => 'CMW', 'description' => 'Cross-member web'],
            ['code' => 'CMX', 'description' => 'Cross-member assembly including clips and fixings'],
            ['code' => 'COS', 'description' => 'Clip-on gen-set clamp socket'],
            ['code' => 'CPA', 'description' => 'Corner post assembly'],
            ['code' => 'CPI', 'description' => 'Corner post inner piece'],
            ['code' => 'CPJ', 'description' => 'Corner post J-bar'],
            ['code' => 'CPL', 'description' => 'Corner post hinge lug'],
            ['code' => 'CPO', 'description' => 'Corner post outer piece'],
            ['code' => 'CPR', 'description' => 'Corner post reinforcement'],
            ['code' => 'CPS', 'description' => 'Corner post single piece'],
            ['code' => 'CRV', 'description' => 'Coving - rivet fixings'],
            ['code' => 'DAA', 'description' => 'Door, complete (without hardware)'],
            ['code' => 'DAH', 'description' => 'Door, complete (with hardware)'],
            ['code' => 'DCS', 'description' => 'Door custom seal point'],
            ['code' => 'DFA', 'description' => 'Door frame assembly'],
            ['code' => 'DFS', 'description' => 'Door/front sill stiffener'],
            ['code' => 'DGR', 'description' => 'Door gear, complete'],
            ['code' => 'DHC', 'description' => 'Door handle catch'],
            ['code' => 'DHL', 'description' => 'Door handle lock assembly'],
            ['code' => 'DHR', 'description' => 'Door handle retainer'],
            ['code' => 'DKA', 'description' => 'Automatic drain'],
            ['code' => 'DKF', 'description' => 'KAZOO BRIDLE'],
            ['code' => 'DKK', 'description' => 'Self-opening drain (Kazoo)'],
            ['code' => 'DKS', 'description' => 'Semi-automatic drain'],
            ['code' => 'DPL', 'description' => 'Door stop/slam (security) plate'],
            ['code' => 'DPR', 'description' => 'Door plate rivets'],
            ['code' => 'DRA', 'description' => 'Drain plug assembly'],
            ['code' => 'DRB', 'description' => 'Bumper'],
            ['code' => 'DRH', 'description' => 'Door chain hook'],
            ['code' => 'DRL', 'description' => 'Door retainer lug'],
            ['code' => 'DRP', 'description' => 'Drain plug'],
            ['code' => 'DRT', 'description' => 'Door retainer'],
            ['code' => 'DSA', 'description' => 'Door striker'],
            ['code' => 'DRN', 'description' => 'ALUMINUM DRAIN'],
            ['code' => 'FAS', 'description' => 'STRUCTURE THAT SUPPORTS THE REFRIGERATION UNIT'],
            ['code' => 'FHS', 'description' => 'Floor  center rail or hat section'],
            ['code' => 'FLA', 'description' => 'Forklift pocket assembly '],
            ['code' => 'FLP', 'description' => 'Forklift pocket top plate '],
            ['code' => 'FLS', 'description' => 'Forklift pocket strap '],
            ['code' => 'FLW', 'description' => 'Fork lift pocket web'],
            ['code' => 'FPP', 'description' => 'Laminated floorboard'],
            ['code' => 'FSA', 'description' => 'Floor support angle'],
            ['code' => 'GIN', 'description' => 'Inner gasket'],
            ['code' => 'GRS', 'description' => 'Gasket retainer strip'],
            ['code' => 'GTA', 'description' => 'Gasket assembly'],
            ['code' => 'GTL', 'description' => 'Specialist gasket'],
            ['code' => 'GTO', 'description' => 'Outer gasket'],
            ['code' => 'HEP', 'description' => 'Header extension plate'],
            ['code' => 'HGA', 'description' => 'Hinge assembly'],
            ['code' => 'HGB', 'description' => 'Hinge blade'],
            ['code' => 'HGP', 'description' => 'Hinge pin'],
            ['code' => 'HHG', 'description' => 'ROTATING LID HINGE (REEFER)'],
            ['code' => 'HWH', 'description' => 'Hardware - Huckbolts'],
            ['code' => 'HWR', 'description' => 'Hardware'],
            ['code' => 'INP', 'description' => 'INTERIOR FRONT PANEL (REEFER)'],
            ['code' => 'KSS', 'description' => 'SPRING'],
            ['code' => 'KTH', 'description' => 'TUBULAR SHAFT THAT ALLOWS THE OPERATION OF THE FRONT AND REAR PANEL'],
            ['code' => 'KTW', 'description' => 'PINÑA (FR)'],
            ['code' => 'LBB', 'description' => 'Locking bar bracket'],
            ['code' => 'LBC', 'description' => 'Locking bar cam'],
            ['code' => 'LBG', 'description' => 'Locking bar guide'],
            ['code' => 'LBH', 'description' => 'Locking bar handle'],
            ['code' => 'LBL', 'description' => 'Locking bar lug'],
            ['code' => 'LBR', 'description' => 'Locking bar rod (tube)'],
            ['code' => 'LBT', 'description' => 'BOLT SECURED WITH COLLAR'],
            ['code' => 'LHH', 'description' => 'Locking bar handle hub'],
            ['code' => 'LLD', 'description' => 'Load line decal'],
            ['code' => 'LSR', 'description' => 'Lashing ring'],
            ['code' => 'MCH', 'description' => 'High Cube Stripes '],
            ['code' => 'MCO', 'description' => 'Cargo container '],
            ['code' => 'MHC', 'description' => 'High Cube Stripes '],
            ['code' => 'MMI', 'description' => 'Mass marking '],
            ['code' => 'MOL', 'description' => 'Owner’s logo '],
            ['code' => 'MPD', 'description' => 'Consolidated data plate '],
            ['code' => 'MPS', 'description' => 'CSC plates'],
            ['code' => 'MRU', 'description' => 'Other markings'],
            ['code' => 'MSD', 'description' => 'Markings-single digit/character'],
            ['code' => 'MSN', 'description' => 'Serial number and check digit'],
            ['code' => 'PAA', 'description' => 'Panel Assembly'],
            ['code' => 'PAF', 'description' => 'Panel-frame'],
            ['code' => 'PDK', 'description' => 'Delamination repair kit'],
            ['code' => 'PEP', 'description' => 'Panel edge profile'],
            ['code' => 'PIC', 'description' => 'Panel inner cladding'],
            ['code' => 'PIM', 'description' => 'Insulation material'],
            ['code' => 'PIS', 'description' => 'Panel - internal stiffener'],
            ['code' => 'PJC', 'description' => 'Panel - joint capping'],
            ['code' => 'POC', 'description' => 'Panel - outer cladding'],
            ['code' => 'PRV', 'description' => 'Internal rivet'],
            ['code' => 'PSL', 'description' => 'Scuff plate/lining'],
            ['code' => 'RAA', 'description' => 'Roof-complete'],
            ['code' => 'RBH', 'description' => 'Roof Bow Holder'],
            ['code' => 'RBO', 'description' => 'Roof Bow'],
            ['code' => 'RCK', 'description' => 'CAM KEEPER'],
            ['code' => 'RCG', 'description' => 'Roof Corner Gusset – Steel '],
            ['code' => 'RCI', 'description' => 'Rail corner protector recess '],
            ['code' => 'RDP', 'description' => 'Rail doubling plate '],
            ['code' => 'RIV', 'description' => 'Internal rivet'],
            ['code' => 'RLA', 'description' => 'Rail assembly'],
            ['code' => 'RLG', 'description' => 'Rail gusset '],
            ['code' => 'RNG', 'description' => 'Rain gutter'],
            ['code' => 'RRT', 'description' => 'Removable/Swinger Header'],
            ['code' => 'RUP', 'description' => 'Rail doubler plate'],
            ['code' => 'RTL', 'description' => 'Gooseneck tunnel rail'],
            ['code' => 'TFA', 'description' => 'T-floor assembly'],
            ['code' => 'TFB', 'description' => 'T-floor angle bar'],
            ['code' => 'TFC', 'description' => 'T-floor casting'],
            ['code' => 'TFD', 'description' => 'T-floor drain'],
            ['code' => 'TFF', 'description' => 'T-floor plate'],
            ['code' => 'TFG', 'description' => 'T-floor gutter'],
            ['code' => 'TFH', 'description' => 'T-floor baffle plate hinge'],
            ['code' => 'TFI', 'description' => 'T-floor strip'],
            ['code' => 'TFP', 'description' => 'T-floor plank'],
            ['code' => 'TFS', 'description' => 'T-floor end seal'],
            ['code' => 'TIC', 'description' => 'TIR Cord'],
            ['code' => 'TIR', 'description' => 'TIR Cord Ring'],
            ['code' => 'TNA', 'description' => 'Tarpaulin Assembly'],
            ['code' => 'TNG', 'description' => 'Tarpaulin Grommet'],
            ['code' => 'TNS', 'description' => 'Tarpaulin - Customs Sealing Point'],
            ['code' => 'TUB', 'description' => 'Tunnel Bolster'],
            ['code' => 'TUC', 'description' => 'Tunnel stiffener (crossmember)'],
            ['code' => 'TUP', 'description' => 'Tunnel Plate '],
            ['code' => 'VRA', 'description' => 'Ventilator assembly'],
        ];

        foreach($components as $component){
            Component::create($component);
        }
    }
}
