<?php

namespace Database\Seeders;

use App\Models\Component;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ComponentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $components = [
            ['code' => 'ASP', 'description' => 'PANEL FRONTAL INTERIOR (REJILLA)'],
            ['code' => 'CFG', 'description' => 'ESQUINERO'],
            ['code' => 'CMA', 'description' => 'TRAVESAÑO DE PISO'],
            ['code' => 'CMF', 'description' => 'PERFIL "T" QUE FIJA EL CROSSMEMBER AL RIEL LATERAL INFERIOR'],
            ['code' => 'CMO', 'description' => 'TRAVESAÑO DE TUNEL'],
            ['code' => 'COS', 'description' => 'SOPORTE ROSCADO PARA ASEGURAR EL CLIPON GENSET'],
            ['code' => 'CPA', 'description' => 'POSTES'],
            ['code' => 'CPJ', 'description' => 'BARRA "J"'],
            ['code' => 'CPL', 'description' => 'PLATINA SOLDADA AL POSTE POSTERIOR DONDE VA SOLDADO EL PIN DE BISAGRA'],
            ['code' => 'DAA', 'description' => 'PUERTA COMPLETA NO INCLUYE ACCESORIOS NI FRIZAS'],
            ['code' => 'DAH', 'description' => 'PUERTA COMPLETA INCLUYE ACCESORIOS Y FRIZAS (NO INCLUYE BISAGRAS)'],
            ['code' => 'DCS', 'description' => 'AGUJERO EN LA ALDABA GIRATORIA Y RETEN PARA COLOCAR EL PRECINTO'],
            ['code' => 'DHC', 'description' => 'ALDABA GIRATORIA'],
            ['code' => 'DHR', 'description' => 'RETEN DE MANIJA DE PUERTA'],
            ['code' => 'DKA', 'description' => 'ENSAMBLE VALVULA DE DRENAJE'],
            ['code' => 'DKF', 'description' => 'BRIDA KAZOO'],
            ['code' => 'DKK', 'description' => 'VALVULA DE DRENAJE'],
            ['code' => 'DPL', 'description' => 'TOPE DE PUERTA'],
            ['code' => 'DRA', 'description' => 'TAPON DE DRENAJE'],
            ['code' => 'DRT', 'description' => 'RETÉN DE PUERTA'],
            ['code' => 'DRN', 'description' => 'DRENAJE DE ALUMINIO'],
            ['code' => 'FAS', 'description' => 'ESTRUCTURA QUE SOPORTA LA UNIDAD DE REFRIGERACION'],
            ['code' => 'FHS', 'description' => 'BARRA OMEGA'],
            ['code' => 'FLA', 'description' => 'BOLSILLO'],
            ['code' => 'FLP', 'description' => 'TAPA DE BOLSILLO'],
            ['code' => 'FLS', 'description' => 'PLANCHA SOLDADA A LA ENTRADA DEL BOLSILLO'],
            ['code' => 'FLW', 'description' => 'RIEL LATERAL DE BOLSILLO'],
            ['code' => 'FPB', 'description' => 'TABLA DE PISO'],
            ['code' => 'FPP', 'description' => 'PISO DE TRIPLAY'],
            ['code' => 'FRS', 'description' => 'RESORTE DE FLAT RACK'],
            ['code' => 'FSA', 'description' => 'ANGULO FIJO AL BOTTOMSIDE RAIL QUE SOPORTA LOS EXTREMOS DEL PISO'],
            ['code' => 'FTP', 'description' => 'PLANCHA PROTECTORA DE PISO'],
            ['code' => 'FWA', 'description' => 'PISO DE MADERA COMPLETO'],
            ['code' => 'GIN', 'description' => 'FRISA INTERNA'],
            ['code' => 'GRS', 'description' => 'PLATINA DE FRIZA'],
            ['code' => 'GTA', 'description' => 'FRIZA DE PUERTA'],
            ['code' => 'GTD', 'description' => 'FRIZA EXTERIOR DE UN CONTENEDOR REFFER'],
            ['code' => 'GTO', 'description' => 'FRISA EXTERNA'],
            ['code' => 'HEP', 'description' => 'PLANCHA PROTECTORA DE TECHO'],
            ['code' => 'HGA', 'description' => 'BISAGRA COMPLETA'],
            ['code' => 'HGB', 'description' => 'ALA DE BISAGRA'],
            ['code' => 'HGP', 'description' => 'PIN DE BISAGRA'],
            ['code' => 'HHG', 'description' => 'BISAGRA DE TAPA GIRATORIA (REFER)'],
            ['code' => 'HPC', 'description' => 'CADENA DE PIN DE OPEN TOP'],
            ['code' => 'HWH', 'description' => 'PERNO CABEZA DE COCHE'],
            ['code' => 'HWR', 'description' => 'PERNO TORNILLOS AUTOROSCANTES'],
            ['code' => 'INP', 'description' => 'PANEL FRONTAL INTERIOR (REFFER)'],
            ['code' => 'KSS', 'description' => 'RESORTE'],
            ['code' => 'KTH', 'description' => 'EJE TUBULAR QUE PERMITE EL ACCIONAMIENTO DE PANEL FRONTAL Y POSTERIOR'],
            ['code' => 'KTW', 'description' => 'PINÑA (FR)'],
            ['code' => 'LBB', 'description' => 'SOPORTE DE BARRA'],
            ['code' => 'LBC', 'description' => 'UÑAS DE PUERTA'],
            ['code' => 'LBG', 'description' => 'GUIA DE BARRA'],
            ['code' => 'LBH', 'description' => 'MANIJA'],
            ['code' => 'LBL', 'description' => 'REMACHE SÓLIDO'],
            ['code' => 'LBR', 'description' => 'BARRA'],
            ['code' => 'LBT', 'description' => 'PERNO ASEGURADO CON COLLAR'],
            ['code' => 'LHH', 'description' => 'SOPORTE DE OREJA DE MANIJA'],
            ['code' => 'LLD', 'description' => 'ETIQUETA DE TOPE DE CARGA'],
            ['code' => 'LSR', 'description' => 'ARO DE TRINCA'],
            ['code' => 'MCH', 'description' => 'MARCAS DE ALTURA'],
            ['code' => 'MCO', 'description' => 'UNIDAD COMPLETA'],
            ['code' => 'MHC', 'description' => 'CINTA CEBRA'],
            ['code' => 'MMI', 'description' => 'MASAS'],
            ['code' => 'MOL', 'description' => 'LOGOTIPO DEL DUEÑO'],
            ['code' => 'MPD', 'description' => 'PLACA DE DESCRIPCIÓN'],
            ['code' => 'MPS', 'description' => 'PLACA CSC'],
            ['code' => 'MRU', 'description' => 'OTRAS MARCAS (TRIÁNGULO, AIRTIGH REEFER, ENTRE OTROS)'],
            ['code' => 'MSD', 'description' => 'NRO O LETRA DE LA SERIE DEL CONTENEDOR'],
            ['code' => 'MSN', 'description' => 'NÚMERO DE SERIE E ISO'],
            ['code' => 'PAA', 'description' => 'PANEL EXTERIOR QUE CUBRE LA BAJA ESTRUCTURA DE UN PISO AISLADO'],
            ['code' => 'PAF', 'description' => 'MARCO DE PUERTA'],
            ['code' => 'PBK', 'description' => 'PANEL FRONTAL'],
            ['code' => 'PEP', 'description' => 'PERFIL DE PVC QUE SELLA LOS EXTREMOS DE UNA PUERTA AISLADA'],
            ['code' => 'PIC', 'description' => 'PANEL INTERIOR DE UN PANEL AISLADO'],
            ['code' => 'PIM', 'description' => 'MATERIAL AISLANTE'],
            ['code' => 'PIP', 'description' => 'CARA INTERNA DE UN PANEL SIMPLE'],
            ['code' => 'PIS', 'description' => 'POSTE LATERAL INTERNO DE LOS PANELES AISLADOS (REFFER)'],
            ['code' => 'PJC', 'description' => 'MOLDE CURVADO QUE SELLA PANEL LATERAL CON TECHO'],
            ['code' => 'POC', 'description' => 'PANEL EXTERIOR'],
            ['code' => 'POP', 'description' => 'CARA EXTERNA DE UN PANEL SIMPLE'],
            ['code' => 'PPW', 'description' => 'PANEL DE TRIPLAY (INTERIOR)'],
            ['code' => 'PRV', 'description' => 'REMACHE'],
            ['code' => 'PSC', 'description' => 'PANEL CORRUGADO'],
            ['code' => 'PSL', 'description' => 'PLANCHA CORRUGADA'],
            ['code' => 'RAA', 'description' => 'TECHO COMPLETO'],
            ['code' => 'RBH', 'description' => 'PIEZAS SOLDADA AL RIEL QUE SOPORTA AL TRAVESAÑO DE TECHO'],
            ['code' => 'RBO', 'description' => 'TRAVESAÑO DE TECHO'],
            ['code' => 'RCK', 'description' => 'CAM KEEPER (GUARDIÁN DE LEVAS)'],
            ['code' => 'RCG', 'description' => 'PLACA PROTECTORA'],
            ['code' => 'RCI', 'description' => 'PROTECTOR DE RIEL'],
            ['code' => 'RDP', 'description' => 'PLANCHA ESQUINERA EN EL TECHO'],
            ['code' => 'RIV', 'description' => 'REMACHE'],
            ['code' => 'RLA', 'description' => 'RIEL SUPERIOR E INFERIOR'],
            ['code' => 'RLG', 'description' => 'ESCUADRA DE REFUERZO EN LOS RIELES'],
            ['code' => 'RNG', 'description' => 'GOTERO DE LLUVIA'],
            ['code' => 'RRT', 'description' => 'RIEL SUPERIOR POSTERIOR REMOVIBLE'],
            ['code' => 'RUP', 'description' => 'PLATINA DE REFUERZO DE RIELES'],
            ['code' => 'RTL', 'description' => 'CUELLO DE GANZO'],
            ['code' => 'SPO', 'description' => 'POSTE LATERAL EXTERNO DE REFUERZO'],
            ['code' => 'TFA', 'description' => 'PISO'],
            ['code' => 'TFB', 'description' => 'DEFLECTOR DE AIRE'],
            ['code' => 'TFC', 'description' => 'RIEL DE CORTINA'],
            ['code' => 'TFD', 'description' => 'DRENAJE DE PISO'],
            ['code' => 'TFF', 'description' => 'DEFLECTORA DE AIRE'],
            ['code' => 'TFG', 'description' => 'MOLDE CURVADO QUE SELLA PANEL LATERAL CON PISO'],
            ['code' => 'TFH', 'description' => 'BISAGRA DE JEBE'],
            ['code' => 'TFI', 'description' => 'REFUERZO DE PISO'],
            ['code' => 'TFP', 'description' => 'SECCIÓN DE PERFIL DE PISO (REFFER)'],
            ['code' => 'TFS', 'description' => 'SELLADO DE PISO'],
            ['code' => 'TIC', 'description' => 'CUERDA DE O/T'],
            ['code' => 'TIR', 'description' => 'AROS SOLDADOS AL RIEL POR DONDE PASA LA CUERDA O/T'],
            ['code' => 'TNA', 'description' => 'LONA O/T'],
            ['code' => 'TNG', 'description' => 'OJALILLOS DE LONA (O/T)'],
            ['code' => 'TNS', 'description' => 'TERMINAL DE CUERDA (O/T)'],
            ['code' => 'TUB', 'description' => 'MIEMBRO TRANSVERSAL QUE VA EN LA PARTE POSTERIOR DEL TUNEL'],
            ['code' => 'TUC', 'description' => 'MIEMBRO TRANSVERSAL QUE SOPORTA LA TAPA DEL TUNEL'],
            ['code' => 'TUP', 'description' => 'TAPA DEL TUNEL'],
            ['code' => 'VRA', 'description' => 'VENTILADOR'],
        ];

        foreach($components as $component){
            Component::create($component);
        }
    }
}
