<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $locations = [
            // ==================== ESTRUCTURA BAJA ====================
            // Lado Derecho (UR)
            ['code' => 'UR1N', 'description' => 'Punto de fijación inferior derecho (posición 1, frontal superior)'],
            ['code' => 'UR2N', 'description' => 'Punto de fijación inferior derecho (posición 2, frontal medio-alto)'],
            ['code' => 'UR3N', 'description' => 'Punto de fijación inferior derecho (posición 3, frontal central)'],
            ['code' => 'UR4N', 'description' => 'Punto de fijación inferior derecho (posición 4, frontal medio-bajo)'],
            ['code' => 'UR5N', 'description' => 'Punto de fijación inferior derecho (posición 5, frontal inferior)'],
            ['code' => 'UR6N', 'description' => 'Punto de fijación inferior derecho (posición 6, trasero superior)'],
            ['code' => 'UR7N', 'description' => 'Punto de fijación inferior derecho (posición 7, trasero medio-alto)'],
            ['code' => 'UR8N', 'description' => 'Punto de fijación inferior derecho (posición 8, trasero central)'],
            ['code' => 'UR9N', 'description' => 'Punto de fijación inferior derecho (posición 9, trasero medio-bajo)'],
            ['code' => 'UR0N', 'description' => 'Punto de fijación inferior derecho (posición 10, trasero inferior)'],
            ['code' => 'UR12', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 2)'],
            ['code' => 'UR13', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 3)'],
            ['code' => 'UR14', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 4)'],
            ['code' => 'UR15', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 5)'],
            ['code' => 'UR16', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 6)'],
            ['code' => 'UR17', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 7)'],
            ['code' => 'UR18', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 8)'],
            ['code' => 'UR19', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 9)'],
            ['code' => 'UR10', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 1 y 10)'],
            ['code' => 'UR23', 'description' => 'Travesaño principal derecho (unión entre posiciones 2 y 3)'],
            ['code' => 'UR24', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 2 y 4)'],
            ['code' => 'UR25', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 2 y 5)'],
            ['code' => 'UR26', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 2 y 6)'],
            ['code' => 'UR27', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 2 y 7)'],
            ['code' => 'UR28', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 2 y 8)'],
            ['code' => 'UR29', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 2 y 9)'],
            ['code' => 'UR20', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 2 y 10)'],
            ['code' => 'UR34', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 3 y 4)'],
            ['code' => 'UR35', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 3 y 5)'],
            ['code' => 'UR36', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 3 y 6)'],
            ['code' => 'UR37', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 3 y 7)'],
            ['code' => 'UR38', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 3 y 8)'],
            ['code' => 'UR39', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 3 y 9)'],
            ['code' => 'UR30', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 3 y 10)'],
            ['code' => 'UR45', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 4 y 5)'],
            ['code' => 'UR46', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 4 y 6)'],
            ['code' => 'UR47', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 4 y 7)'],
            ['code' => 'UR48', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 4 y 8)'],
            ['code' => 'UR49', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 4 y 9)'],
            ['code' => 'UR56', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 5 y 6)'],
            ['code' => 'UR57', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 5 y 7)'],
            ['code' => 'UR58', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 5 y 8)'],
            ['code' => 'UR59', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 5 y 9)'],
            ['code' => 'UR50', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 5 y 10)'],
            ['code' => 'UR67', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 6 y 7)'],
            ['code' => 'UR68', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 6 y 8)'],
            ['code' => 'UR69', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 6 y 9)'],
            ['code' => 'UR60', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 6 y 10)'],
            ['code' => 'UR78', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 7 y 8)'],
            ['code' => 'UR79', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 7 y 9)'],
            ['code' => 'UR70', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 7 y 10)'],
            ['code' => 'UR89', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 8 y 9)'],
            ['code' => 'UR80', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 8 y 10)'],
            ['code' => 'UR90', 'description' => 'Refuerzo estructural derecho (unión entre posiciones 9 y 10)'],

            // Centro (UX)
            ['code' => 'UX1N', 'description' => 'Punto de anclaje central inferior (posición 1, frontal superior)'],
            ['code' => 'UX2N', 'description' => 'Punto de anclaje central inferior (posición 2, frontal medio-alto)'],
            ['code' => 'UX3N', 'description' => 'Punto de anclaje central inferior (posición 3, frontal central)'],
            ['code' => 'UX4N', 'description' => 'Punto de anclaje central inferior (posición 4, frontal medio-bajo)'],
            ['code' => 'UX5N', 'description' => 'Punto de anclaje central inferior (posición 5, frontal inferior)'],
            ['code' => 'UX6N', 'description' => 'Punto de anclaje central inferior (posición 6, trasero superior)'],
            ['code' => 'UX7N', 'description' => 'Punto de anclaje central inferior (posición 7, trasero medio-alto)'],
            ['code' => 'UX8N', 'description' => 'Punto de anclaje central inferior (posición 8, trasero central)'],
            ['code' => 'UX9N', 'description' => 'Punto de anclaje central inferior (posición 9, trasero medio-bajo)'],
            ['code' => 'UX0N', 'description' => 'Punto de anclaje central inferior (posición 10, trasero inferior)'],
            ['code' => 'UX12', 'description' => 'Viga maestra central (unión entre posiciones 1 y 2)'],
            ['code' => 'UX13', 'description' => 'Refuerzo central (unión entre posiciones 1 y 3)'],
            ['code' => 'UX14', 'description' => 'Refuerzo central (unión entre posiciones 1 y 4)'],
            ['code' => 'UX15', 'description' => 'Refuerzo central (unión entre posiciones 1 y 5)'],
            ['code' => 'UX16', 'description' => 'Refuerzo central (unión entre posiciones 1 y 6)'],
            ['code' => 'UX17', 'description' => 'Refuerzo central (unión entre posiciones 1 y 7)'],
            ['code' => 'UX18', 'description' => 'Refuerzo central (unión entre posiciones 1 y 8)'],
            ['code' => 'UX19', 'description' => 'Refuerzo central (unión entre posiciones 1 y 9)'],
            ['code' => 'UX10', 'description' => 'Refuerzo central (unión entre posiciones 1 y 10)'],
            ['code' => 'UX23', 'description' => 'Travesaño central principal (unión entre posiciones 2 y 3)'],
            ['code' => 'UX24', 'description' => 'Refuerzo central (unión entre posiciones 2 y 4)'],
            ['code' => 'UX25', 'description' => 'Refuerzo central (unión entre posiciones 2 y 5)'],
            ['code' => 'UX26', 'description' => 'Refuerzo central (unión entre posiciones 2 y 6)'],
            ['code' => 'UX27', 'description' => 'Refuerzo central (unión entre posiciones 2 y 7)'],
            ['code' => 'UX28', 'description' => 'Refuerzo central (unión entre posiciones 2 y 8)'],
            ['code' => 'UX29', 'description' => 'Refuerzo central (unión entre posiciones 2 y 9)'],
            ['code' => 'UX20', 'description' => 'Refuerzo central (unión entre posiciones 2 y 10)'],
            ['code' => 'UX34', 'description' => 'Viga transversal de carga (unión entre posiciones 3 y 4)'],
            ['code' => 'UX35', 'description' => 'Refuerzo central (unión entre posiciones 3 y 5)'],
            ['code' => 'UX36', 'description' => 'Refuerzo central (unión entre posiciones 3 y 6)'],
            ['code' => 'UX37', 'description' => 'Refuerzo central (unión entre posiciones 3 y 7)'],
            ['code' => 'UX38', 'description' => 'Refuerzo central (unión entre posiciones 3 y 8)'],
            ['code' => 'UX39', 'description' => 'Refuerzo central (unión entre posiciones 3 y 9)'],
            ['code' => 'UX30', 'description' => 'Refuerzo central (unión entre posiciones 3 y 10)'],
            ['code' => 'UX45', 'description' => 'Refuerzo de piso central (unión entre posiciones 4 y 5)'],
            ['code' => 'UX46', 'description' => 'Refuerzo central (unión entre posiciones 4 y 6)'],
            ['code' => 'UX47', 'description' => 'Refuerzo central (unión entre posiciones 4 y 7)'],
            ['code' => 'UX48', 'description' => 'Refuerzo central (unión entre posiciones 4 y 8)'],
            ['code' => 'UX49', 'description' => 'Refuerzo central (unión entre posiciones 4 y 9)'],
            ['code' => 'UX56', 'description' => 'Conexión de piso con chasis (unión entre posiciones 5 y 6)'],
            ['code' => 'UX57', 'description' => 'Refuerzo central (unión entre posiciones 5 y 7)'],
            ['code' => 'UX58', 'description' => 'Refuerzo central (unión entre posiciones 5 y 8)'],
            ['code' => 'UX59', 'description' => 'Refuerzo central (unión entre posiciones 5 y 9)'],
            ['code' => 'UX50', 'description' => 'Refuerzo central (unión entre posiciones 5 y 10)'],
            ['code' => 'UX67', 'description' => 'Refuerzo central (unión entre posiciones 6 y 7)'],
            ['code' => 'UX68', 'description' => 'Refuerzo central (unión entre posiciones 6 y 8)'],
            ['code' => 'UX69', 'description' => 'Refuerzo central (unión entre posiciones 6 y 9)'],
            ['code' => 'UX60', 'description' => 'Refuerzo central (unión entre posiciones 6 y 10)'],
            ['code' => 'UX78', 'description' => 'Refuerzo central (unión entre posiciones 7 y 8)'],
            ['code' => 'UX79', 'description' => 'Refuerzo central (unión entre posiciones 7 y 9)'],
            ['code' => 'UX70', 'description' => 'Refuerzo central (unión entre posiciones 7 y 10)'],
            ['code' => 'UX89', 'description' => 'Refuerzo central (unión entre posiciones 8 y 9)'],
            ['code' => 'UX80', 'description' => 'Refuerzo central (unión entre posiciones 8 y 10)'],
            ['code' => 'UX90', 'description' => 'Refuerzo central (unión entre posiciones 9 y 10)'],

            // Lado Izquierdo (UL)
            ['code' => 'UL1N', 'description' => 'Punto de fijación inferior izquierdo (posición 1, frontal superior)'],
            ['code' => 'UL2N', 'description' => 'Punto de fijación inferior izquierdo (posición 2, frontal medio-alto)'],
            ['code' => 'UL3N', 'description' => 'Punto de fijación inferior izquierdo (posición 3, frontal central)'],
            ['code' => 'UL4N', 'description' => 'Punto de fijación inferior izquierdo (posición 4, frontal medio-bajo)'],
            ['code' => 'UL5N', 'description' => 'Punto de fijación inferior izquierdo (posición 5, frontal inferior)'],
            ['code' => 'UL6N', 'description' => 'Punto de fijación inferior izquierdo (posición 6, trasero superior)'],
            ['code' => 'UL7N', 'description' => 'Punto de fijación inferior izquierdo (posición 7, trasero medio-alto)'],
            ['code' => 'UL8N', 'description' => 'Punto de fijación inferior izquierdo (posición 8, trasero central)'],
            ['code' => 'UL9N', 'description' => 'Punto de fijación inferior izquierdo (posición 9, trasero medio-bajo)'],
            ['code' => 'UL0N', 'description' => 'Punto de fijación inferior izquierdo (posición 10, trasero inferior)'],
            ['code' => 'UL12', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 2)'],
            ['code' => 'UL13', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 3)'],
            ['code' => 'UL14', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 4)'],
            ['code' => 'UL15', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 5)'],
            ['code' => 'UL16', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 6)'],
            ['code' => 'UL17', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 7)'],
            ['code' => 'UL18', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 8)'],
            ['code' => 'UL19', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 9)'],
            ['code' => 'UL10', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 1 y 10)'],
            ['code' => 'UL23', 'description' => 'Travesaño principal izquierdo (unión entre posiciones 2 y 3)'],
            ['code' => 'UL24', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 2 y 4)'],
            ['code' => 'UL25', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 2 y 5)'],
            ['code' => 'UL26', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 2 y 6)'],
            ['code' => 'UL27', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 2 y 7)'],
            ['code' => 'UL28', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 2 y 8)'],
            ['code' => 'UL29', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 2 y 9)'],
            ['code' => 'UL20', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 2 y 10)'],
            ['code' => 'UL34', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 3 y 4)'],
            ['code' => 'UL35', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 3 y 5)'],
            ['code' => 'UL36', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 3 y 6)'],
            ['code' => 'UL37', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 3 y 7)'],
            ['code' => 'UL38', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 3 y 8)'],
            ['code' => 'UL39', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 3 y 9)'],
            ['code' => 'UL30', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 3 y 10)'],
            ['code' => 'UL45', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 4 y 5)'],
            ['code' => 'UL46', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 4 y 6)'],
            ['code' => 'UL47', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 4 y 7)'],
            ['code' => 'UL48', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 4 y 8)'],
            ['code' => 'UL49', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 4 y 9)'],
            ['code' => 'UL56', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 5 y 6)'],
            ['code' => 'UL57', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 5 y 7)'],
            ['code' => 'UL58', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 5 y 8)'],
            ['code' => 'UL59', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 5 y 9)'],
            ['code' => 'UL50', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 5 y 10)'],
            ['code' => 'UL67', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 6 y 7)'],
            ['code' => 'UL68', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 6 y 8)'],
            ['code' => 'UL69', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 6 y 9)'],
            ['code' => 'UL60', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 6 y 10)'],
            ['code' => 'UL78', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 7 y 8)'],
            ['code' => 'UL79', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 7 y 9)'],
            ['code' => 'UL70', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 7 y 10)'],
            ['code' => 'UL89', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 8 y 9)'],
            ['code' => 'UL80', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 8 y 10)'],
            ['code' => 'UL90', 'description' => 'Refuerzo estructural izquierdo (unión entre posiciones 9 y 10)'],

            // ==================== PUERTA ====================
            // Paneles (DB)
            ['code' => 'DB1N', 'description' => 'Panel superior frontal de la puerta (parte izquierda, cerca del techo)'],
            ['code' => 'DB2N', 'description' => 'Panel central frontal de la puerta (izquierda, altura media)'],
            ['code' => 'DB3N', 'description' => 'Panel inferior frontal de la puerta (izquierda, cerca del piso)'],
            ['code' => 'DB4N', 'description' => 'Panel superior trasero de la puerta (parte derecha, cerca del techo)'],
            ['code' => 'DB23', 'description' => 'Travesaño estructural horizontal de la puerta (soporte central)'],

            // Herrajes (DX)
            ['code' => 'DX1N', 'description' => 'Herrajes superiores de la puerta (bisagras, cerraduras, lado izquierdo)'],
            ['code' => 'DX2N', 'description' => 'Herrajes centrales de la puerta (barra de cierre, mecanismos)'],
            ['code' => 'DX3N', 'description' => 'Herrajes inferiores de la puerta (soportes de piso)'],
            ['code' => 'DX4N', 'description' => 'Sellos de goma superiores de la puerta (evitan filtraciones)'],
            ['code' => 'DX23', 'description' => 'Mecanismo principal de cierre/aseguramiento de la puerta'],

            // Umbrales (DT)
            ['code' => 'DT1N', 'description' => 'Umbral superior de la puerta (parte metálica de entrada/salida)'],
            ['code' => 'DT2N', 'description' => 'Umbral central de la puerta (guías para apilamiento)'],
            ['code' => 'DT3N', 'description' => 'Umbral inferior de la puerta (contacto con el piso/chasis)'],
            ['code' => 'DT4N', 'description' => 'Marco lateral de la puerta (refuerzo estructural)'],
            ['code' => 'DT23', 'description' => 'Conjunto completo de bisagras de la puerta'],

            // ==================== TECHO ====================
            // Lado Derecho (TR)
            ['code' => 'TR1N', 'description' => 'Panel de techo derecho (posición 1, frontal superior)'],
            ['code' => 'TR2N', 'description' => 'Panel de techo derecho (posición 2, frontal medio-alto)'],
            ['code' => 'TR3N', 'description' => 'Panel de techo derecho (posición 3, frontal central)'],
            ['code' => 'TR4N', 'description' => 'Panel de techo derecho (posición 4, frontal medio-bajo)'],
            ['code' => 'TR5N', 'description' => 'Panel de techo derecho (posición 5, frontal inferior)'],
            ['code' => 'TR6N', 'description' => 'Panel de techo derecho (posición 6, trasero superior)'],
            ['code' => 'TR7N', 'description' => 'Panel de techo derecho (posición 7, trasero medio-alto)'],
            ['code' => 'TR8N', 'description' => 'Panel de techo derecho (posición 8, trasero central)'],
            ['code' => 'TR9N', 'description' => 'Panel de techo derecho (posición 9, trasero medio-bajo)'],
            ['code' => 'TR0N', 'description' => 'Panel de techo derecho (posición 10, trasero inferior)'],
            ['code' => 'TR12', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 1 y 2)'],
            ['code' => 'TR13', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 3)'],
            ['code' => 'TR14', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 4)'],
            ['code' => 'TR15', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 5)'],
            ['code' => 'TR16', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 1 y 6)'],
            ['code' => 'TR17', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 7)'],
            ['code' => 'TR18', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 8)'],
            ['code' => 'TR19', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 9)'],
            ['code' => 'TR10', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 10)'],
            ['code' => 'TR23', 'description' => 'Travesaño principal derecho (unión entre posiciones 2 y 3)'],
            ['code' => 'TR24', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 4)'],
            ['code' => 'TR25', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 5)'],
            ['code' => 'TR26', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 2 y 6)'],
            ['code' => 'TR27', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 7)'],
            ['code' => 'TR28', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 8)'],
            ['code' => 'TR29', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 9)'],
            ['code' => 'TR20', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 10)'],
            ['code' => 'TR34', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 3 y 4)'],
            ['code' => 'TR35', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 5)'],
            ['code' => 'TR36', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 3 y 6)'],
            ['code' => 'TR37', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 7)'],
            ['code' => 'TR38', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 8)'],
            ['code' => 'TR39', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 9)'],
            ['code' => 'TR30', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 10)'],
            ['code' => 'TR45', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 4 y 5)'],
            ['code' => 'TR46', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 4 y 6)'],
            ['code' => 'TR47', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 4 y 7)'],
            ['code' => 'TR48', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 4 y 8)'],
            ['code' => 'TR49', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 4 y 9)'],
            ['code' => 'TR56', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 5 y 6)'],
            ['code' => 'TR57', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 5 y 7)'],
            ['code' => 'TR58', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 5 y 8)'],
            ['code' => 'TR59', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 5 y 9)'],
            ['code' => 'TR50', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 5 y 10)'],
            ['code' => 'TR67', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 6 y 7)'],
            ['code' => 'TR68', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 6 y 8)'],
            ['code' => 'TR69', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 6 y 9)'],
            ['code' => 'TR60', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 6 y 10)'],
            ['code' => 'TR78', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 7 y 8)'],
            ['code' => 'TR79', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 7 y 9)'],
            ['code' => 'TR70', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 7 y 10)'],
            ['code' => 'TR89', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 8 y 9)'],
            ['code' => 'TR80', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 8 y 10)'],
            ['code' => 'TR90', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 9 y 10)'],

            // Centro (TX)
            ['code' => 'TX1N', 'description' => 'Panel de techo central (posición 1, frontal superior)'],
            ['code' => 'TX2N', 'description' => 'Panel de techo central (posición 2, frontal medio-alto)'],
            ['code' => 'TX3N', 'description' => 'Panel de techo central (posición 3, frontal central)'],
            ['code' => 'TX4N', 'description' => 'Panel de techo central (posición 4, frontal medio-bajo)'],
            ['code' => 'TX5N', 'description' => 'Panel de techo central (posición 5, frontal inferior)'],
            ['code' => 'TX6N', 'description' => 'Panel de techo central (posición 6, trasero superior)'],
            ['code' => 'TX7N', 'description' => 'Panel de techo central (posición 7, trasero medio-alto)'],
            ['code' => 'TX8N', 'description' => 'Panel de techo central (posición 8, trasero central)'],
            ['code' => 'TX9N', 'description' => 'Panel de techo central (posición 9, trasero medio-bajo)'],
            ['code' => 'TX0N', 'description' => 'Panel de techo central (posición 10, trasero inferior)'],
            ['code' => 'TX12', 'description' => 'Viga maestra central (unión entre posiciones 1 y 2)'],
            ['code' => 'TX13', 'description' => 'Refuerzo diagonal central (unión entre posiciones 1 y 3)'],
            ['code' => 'TX14', 'description' => 'Refuerzo diagonal central (unión entre posiciones 1 y 4)'],
            ['code' => 'TX15', 'description' => 'Refuerzo diagonal central (unión entre posiciones 1 y 5)'],
            ['code' => 'TX16', 'description' => 'Refuerzo transversal central (unión entre posiciones 1 y 6)'],
            ['code' => 'TX17', 'description' => 'Refuerzo diagonal central (unión entre posiciones 1 y 7)'],
            ['code' => 'TX18', 'description' => 'Refuerzo diagonal central (unión entre posiciones 1 y 8)'],
            ['code' => 'TX19', 'description' => 'Refuerzo diagonal central (unión entre posiciones 1 y 9)'],
            ['code' => 'TX10', 'description' => 'Refuerzo diagonal central (unión entre posiciones 1 y 10)'],
            ['code' => 'TX23', 'description' => 'Travesaño principal central (unión entre posiciones 2 y 3)'],
            ['code' => 'TX24', 'description' => 'Refuerzo diagonal central (unión entre posiciones 2 y 4)'],
            ['code' => 'TX25', 'description' => 'Refuerzo diagonal central (unión entre posiciones 2 y 5)'],
            ['code' => 'TX26', 'description' => 'Refuerzo transversal central (unión entre posiciones 2 y 6)'],
            ['code' => 'TX27', 'description' => 'Refuerzo diagonal central (unión entre posiciones 2 y 7)'],
            ['code' => 'TX28', 'description' => 'Refuerzo diagonal central (unión entre posiciones 2 y 8)'],
            ['code' => 'TX29', 'description' => 'Refuerzo diagonal central (unión entre posiciones 2 y 9)'],
            ['code' => 'TX20', 'description' => 'Refuerzo diagonal central (unión entre posiciones 2 y 10)'],
            ['code' => 'TX34', 'description' => 'Refuerzo longitudinal central (unión entre posiciones 3 y 4)'],
            ['code' => 'TX35', 'description' => 'Refuerzo diagonal central (unión entre posiciones 3 y 5)'],
            ['code' => 'TX36', 'description' => 'Refuerzo transversal central (unión entre posiciones 3 y 6)'],
            ['code' => 'TX37', 'description' => 'Refuerzo diagonal central (unión entre posiciones 3 y 7)'],
            ['code' => 'TX38', 'description' => 'Refuerzo diagonal central (unión entre posiciones 3 y 8)'],
            ['code' => 'TX39', 'description' => 'Refuerzo diagonal central (unión entre posiciones 3 y 9)'],
            ['code' => 'TX30', 'description' => 'Refuerzo diagonal central (unión entre posiciones 3 y 10)'],
            ['code' => 'TX45', 'description' => 'Refuerzo longitudinal central (unión entre posiciones 4 y 5)'],
            ['code' => 'TX46', 'description' => 'Refuerzo transversal central (unión entre posiciones 4 y 6)'],
            ['code' => 'TX47', 'description' => 'Refuerzo diagonal central (unión entre posiciones 4 y 7)'],
            ['code' => 'TX48', 'description' => 'Refuerzo diagonal central (unión entre posiciones 4 y 8)'],
            ['code' => 'TX49', 'description' => 'Refuerzo diagonal central (unión entre posiciones 4 y 9)'],
            ['code' => 'TX56', 'description' => 'Refuerzo transversal central (unión entre posiciones 5 y 6)'],
            ['code' => 'TX57', 'description' => 'Refuerzo diagonal central (unión entre posiciones 5 y 7)'],
            ['code' => 'TX58', 'description' => 'Refuerzo diagonal central (unión entre posiciones 5 y 8)'],
            ['code' => 'TX59', 'description' => 'Refuerzo diagonal central (unión entre posiciones 5 y 9)'],
            ['code' => 'TX50', 'description' => 'Refuerzo diagonal central (unión entre posiciones 5 y 10)'],
            ['code' => 'TX67', 'description' => 'Refuerzo longitudinal central (unión entre posiciones 6 y 7)'],
            ['code' => 'TX68', 'description' => 'Refuerzo diagonal central (unión entre posiciones 6 y 8)'],
            ['code' => 'TX69', 'description' => 'Refuerzo diagonal central (unión entre posiciones 6 y 9)'],
            ['code' => 'TX60', 'description' => 'Refuerzo diagonal central (unión entre posiciones 6 y 10)'],
            ['code' => 'TX78', 'description' => 'Refuerzo longitudinal central (unión entre posiciones 7 y 8)'],
            ['code' => 'TX79', 'description' => 'Refuerzo diagonal central (unión entre posiciones 7 y 9)'],
            ['code' => 'TX70', 'description' => 'Refuerzo diagonal central (unión entre posiciones 7 y 10)'],
            ['code' => 'TX89', 'description' => 'Refuerzo longitudinal central (unión entre posiciones 8 y 9)'],
            ['code' => 'TX80', 'description' => 'Refuerzo diagonal central (unión entre posiciones 8 y 10)'],
            ['code' => 'TX90', 'description' => 'Refuerzo longitudinal central (unión entre posiciones 9 y 10)'],

            // Lado Izquierdo (TL)
            ['code' => 'TL1N', 'description' => 'Panel de techo izquierdo (posición 1, frontal superior)'],
            ['code' => 'TL2N', 'description' => 'Panel de techo izquierdo (posición 2, frontal medio-alto)'],
            ['code' => 'TL3N', 'description' => 'Panel de techo izquierdo (posición 3, frontal central)'],
            ['code' => 'TL4N', 'description' => 'Panel de techo izquierdo (posición 4, frontal medio-bajo)'],
            ['code' => 'TL5N', 'description' => 'Panel de techo izquierdo (posición 5, frontal inferior)'],
            ['code' => 'TL6N', 'description' => 'Panel de techo izquierdo (posición 6, trasero superior)'],
            ['code' => 'TL7N', 'description' => 'Panel de techo izquierdo (posición 7, trasero medio-alto)'],
            ['code' => 'TL8N', 'description' => 'Panel de techo izquierdo (posición 8, trasero central)'],
            ['code' => 'TL9N', 'description' => 'Panel de techo izquierdo (posición 9, trasero medio-bajo)'],
            ['code' => 'TL0N', 'description' => 'Panel de techo izquierdo (posición 10, trasero inferior)'],
            ['code' => 'TL12', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 1 y 2)'],
            ['code' => 'TL13', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 3)'],
            ['code' => 'TL14', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 4)'],
            ['code' => 'TL15', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 5)'],
            ['code' => 'TL16', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 1 y 6)'],
            ['code' => 'TL17', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 7)'],
            ['code' => 'TL18', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 8)'],
            ['code' => 'TL19', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 9)'],
            ['code' => 'TL10', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 10)'],
            ['code' => 'TL23', 'description' => 'Travesaño principal izquierdo (unión entre posiciones 2 y 3)'],
            ['code' => 'TL24', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 4)'],
            ['code' => 'TL25', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 5)'],
            ['code' => 'TL26', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 2 y 6)'],
            ['code' => 'TL27', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 7)'],
            ['code' => 'TL28', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 8)'],
            ['code' => 'TL29', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 9)'],
            ['code' => 'TL20', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 10)'],
            ['code' => 'TL34', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 3 y 4)'],
            ['code' => 'TL35', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 5)'],
            ['code' => 'TL36', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 3 y 6)'],
            ['code' => 'TL37', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 7)'],
            ['code' => 'TL38', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 8)'],
            ['code' => 'TL39', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 9)'],
            ['code' => 'TL30', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 10)'],
            ['code' => 'TL45', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 4 y 5)'],
            ['code' => 'TL46', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 4 y 6)'],
            ['code' => 'TL47', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 4 y 7)'],
            ['code' => 'TL48', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 4 y 8)'],
            ['code' => 'TL49', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 4 y 9)'],
            ['code' => 'TL56', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 5 y 6)'],
            ['code' => 'TL57', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 5 y 7)'],
            ['code' => 'TL58', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 5 y 8)'],
            ['code' => 'TL59', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 5 y 9)'],
            ['code' => 'TL50', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 5 y 10)'],
            ['code' => 'TL67', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 6 y 7)'],
            ['code' => 'TL68', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 6 y 8)'],
            ['code' => 'TL69', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 6 y 9)'],
            ['code' => 'TL60', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 6 y 10)'],
            ['code' => 'TL78', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 7 y 8)'],
            ['code' => 'TL79', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 7 y 9)'],
            ['code' => 'TL70', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 7 y 10)'],
            ['code' => 'TL89', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 8 y 9)'],
            ['code' => 'TL80', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 8 y 10)'],
            ['code' => 'TL90', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 9 y 10)'],

            // ==================== LATERALES ====================
            // Lado Derecho (RB)
            ['code' => 'RB1N', 'description' => 'Panel lateral derecho (posición 1, frontal superior)'],
            ['code' => 'RB2N', 'description' => 'Panel lateral derecho (posición 2, frontal medio-alto)'],
            ['code' => 'RB3N', 'description' => 'Panel lateral derecho (posición 3, frontal central)'],
            ['code' => 'RB4N', 'description' => 'Panel lateral derecho (posición 4, frontal medio-bajo)'],
            ['code' => 'RB5N', 'description' => 'Panel lateral derecho (posición 5, frontal inferior)'],
            ['code' => 'RB6N', 'description' => 'Panel lateral derecho (posición 6, trasero superior)'],
            ['code' => 'RB7N', 'description' => 'Panel lateral derecho (posición 7, trasero medio-alto)'],
            ['code' => 'RB8N', 'description' => 'Panel lateral derecho (posición 8, trasero central)'],
            ['code' => 'RB9N', 'description' => 'Panel lateral derecho (posición 9, trasero medio-bajo)'],
            ['code' => 'RB0N', 'description' => 'Panel lateral derecho (posición 10, trasero inferior)'],
            ['code' => 'RB12', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 1 y 2)'],
            ['code' => 'RB13', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 3)'],
            ['code' => 'RB14', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 4)'],
            ['code' => 'RB15', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 5)'],
            ['code' => 'RB16', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 1 y 6)'],
            ['code' => 'RB17', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 7)'],
            ['code' => 'RB18', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 8)'],
            ['code' => 'RB19', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 1 y 9)'],
            ['code' => 'RB23', 'description' => 'Travesaño principal derecho (unión entre posiciones 2 y 3)'],
            ['code' => 'RB24', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 4)'],
            ['code' => 'RB25', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 5)'],
            ['code' => 'RB26', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 2 y 6)'],
            ['code' => 'RB27', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 7)'],
            ['code' => 'RB28', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 8)'],
            ['code' => 'RB29', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 2 y 9)'],
            ['code' => 'RB34', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 3 y 4)'],
            ['code' => 'RB35', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 5)'],
            ['code' => 'RB36', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 3 y 6)'],
            ['code' => 'RB37', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 7)'],
            ['code' => 'RB38', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 8)'],
            ['code' => 'RB39', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 3 y 9)'],
            ['code' => 'RB45', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 4 y 5)'],
            ['code' => 'RB46', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 4 y 6)'],
            ['code' => 'RB47', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 4 y 7)'],
            ['code' => 'RB48', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 4 y 8)'],
            ['code' => 'RB49', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 4 y 9)'],
            ['code' => 'RB56', 'description' => 'Refuerzo transversal derecho (unión entre posiciones 5 y 6)'],
            ['code' => 'RB57', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 5 y 7)'],
            ['code' => 'RB58', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 5 y 8)'],
            ['code' => 'RB59', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 5 y 9)'],
            ['code' => 'RB67', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 6 y 7)'],
            ['code' => 'RB68', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 6 y 8)'],
            ['code' => 'RB69', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 6 y 9)'],
            ['code' => 'RB78', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 7 y 8)'],
            ['code' => 'RB79', 'description' => 'Refuerzo diagonal derecho (unión entre posiciones 7 y 9)'],
            ['code' => 'RB89', 'description' => 'Refuerzo longitudinal derecho (unión entre posiciones 8 y 9)'],

            // Centro (RX)
            ['code' => 'RX1N', 'description' => 'Unión central derecha (posición 1, frontal superior)'],
            ['code' => 'RX2N', 'description' => 'Unión central derecha (posición 2, frontal medio-alto)'],
            ['code' => 'RX3N', 'description' => 'Unión central derecha (posición 3, frontal central)'],
            ['code' => 'RX4N', 'description' => 'Unión central derecha (posición 4, frontal medio-bajo)'],
            ['code' => 'RX5N', 'description' => 'Unión central derecha (posición 5, frontal inferior)'],
            ['code' => 'RX6N', 'description' => 'Unión central derecha (posición 6, trasero superior)'],
            ['code' => 'RX7N', 'description' => 'Unión central derecha (posición 7, trasero medio-alto)'],
            ['code' => 'RX8N', 'description' => 'Unión central derecha (posición 8, trasero central)'],
            ['code' => 'RX9N', 'description' => 'Unión central derecha (posición 9, trasero medio-bajo)'],
            ['code' => 'RX0N', 'description' => 'Unión central derecha (posición 10, trasero inferior)'],
            ['code' => 'RX12', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 2)'],
            ['code' => 'RX13', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 3)'],
            ['code' => 'RX14', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 4)'],
            ['code' => 'RX15', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 5)'],
            ['code' => 'RX16', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 6)'],
            ['code' => 'RX17', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 7)'],
            ['code' => 'RX18', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 8)'],
            ['code' => 'RX19', 'description' => 'Refuerzo central derecho (unión entre posiciones 1 y 9)'],
            ['code' => 'RX23', 'description' => 'Travesaño central derecho (unión entre posiciones 2 y 3)'],
            ['code' => 'RX24', 'description' => 'Refuerzo central derecho (unión entre posiciones 2 y 4)'],
            ['code' => 'RX25', 'description' => 'Refuerzo central derecho (unión entre posiciones 2 y 5)'],
            ['code' => 'RX26', 'description' => 'Refuerzo central derecho (unión entre posiciones 2 y 6)'],
            ['code' => 'RX27', 'description' => 'Refuerzo central derecho (unión entre posiciones 2 y 7)'],
            ['code' => 'RX28', 'description' => 'Refuerzo central derecho (unión entre posiciones 2 y 8)'],
            ['code' => 'RX29', 'description' => 'Refuerzo central derecho (unión entre posiciones 2 y 9)'],
            ['code' => 'RX34', 'description' => 'Refuerzo central derecho (unión entre posiciones 3 y 4)'],
            ['code' => 'RX35', 'description' => 'Refuerzo central derecho (unión entre posiciones 3 y 5)'],
            ['code' => 'RX36', 'description' => 'Refuerzo central derecho (unión entre posiciones 3 y 6)'],
            ['code' => 'RX37', 'description' => 'Refuerzo central derecho (unión entre posiciones 3 y 7)'],
            ['code' => 'RX38', 'description' => 'Refuerzo central derecho (unión entre posiciones 3 y 8)'],
            ['code' => 'RX39', 'description' => 'Refuerzo central derecho (unión entre posiciones 3 y 9)'],
            ['code' => 'RX45', 'description' => 'Refuerzo central derecho (unión entre posiciones 4 y 5)'],
            ['code' => 'RX46', 'description' => 'Refuerzo central derecho (unión entre posiciones 4 y 6)'],
            ['code' => 'RX47', 'description' => 'Refuerzo central derecho (unión entre posiciones 4 y 7)'],
            ['code' => 'RX48', 'description' => 'Refuerzo central derecho (unión entre posiciones 4 y 8)'],
            ['code' => 'RX49', 'description' => 'Refuerzo central derecho (unión entre posiciones 4 y 9)'],
            ['code' => 'RX56', 'description' => 'Refuerzo central derecho (unión entre posiciones 5 y 6)'],
            ['code' => 'RX57', 'description' => 'Refuerzo central derecho (unión entre posiciones 5 y 7)'],
            ['code' => 'RX58', 'description' => 'Refuerzo central derecho (unión entre posiciones 5 y 8)'],
            ['code' => 'RX59', 'description' => 'Refuerzo central derecho (unión entre posiciones 5 y 9)'],
            ['code' => 'RX67', 'description' => 'Refuerzo central derecho (unión entre posiciones 6 y 7)'],
            ['code' => 'RX68', 'description' => 'Refuerzo central derecho (unión entre posiciones 6 y 8)'],
            ['code' => 'RX69', 'description' => 'Refuerzo central derecho (unión entre posiciones 6 y 9)'],
            ['code' => 'RX78', 'description' => 'Refuerzo central derecho (unión entre posiciones 7 y 8)'],
            ['code' => 'RX79', 'description' => 'Refuerzo central derecho (unión entre posiciones 7 y 9)'],
            ['code' => 'RX89', 'description' => 'Refuerzo central derecho (unión entre posiciones 8 y 9)'],

            // Lado Izquierdo (LB)
            ['code' => 'LB1N', 'description' => 'Panel lateral izquierdo (posición 1, frontal superior)'],
            ['code' => 'LB2N', 'description' => 'Panel lateral izquierdo (posición 2, frontal medio-alto)'],
            ['code' => 'LB3N', 'description' => 'Panel lateral izquierdo (posición 3, frontal central)'],
            ['code' => 'LB4N', 'description' => 'Panel lateral izquierdo (posición 4, frontal medio-bajo)'],
            ['code' => 'LB5N', 'description' => 'Panel lateral izquierdo (posición 5, frontal inferior)'],
            ['code' => 'LB6N', 'description' => 'Panel lateral izquierdo (posición 6, trasero superior)'],
            ['code' => 'LB7N', 'description' => 'Panel lateral izquierdo (posición 7, trasero medio-alto)'],
            ['code' => 'LB8N', 'description' => 'Panel lateral izquierdo (posición 8, trasero central)'],
            ['code' => 'LB9N', 'description' => 'Panel lateral izquierdo (posición 9, trasero medio-bajo)'],
            ['code' => 'LB0N', 'description' => 'Panel lateral izquierdo (posición 10, trasero inferior)'],
            ['code' => 'LB12', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 1 y 2)'],
            ['code' => 'LB13', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 3)'],
            ['code' => 'LB14', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 4)'],
            ['code' => 'LB15', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 5)'],
            ['code' => 'LB16', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 1 y 6)'],
            ['code' => 'LB17', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 7)'],
            ['code' => 'LB18', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 8)'],
            ['code' => 'LB19', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 1 y 9)'],
            ['code' => 'LB23', 'description' => 'Travesaño principal izquierdo (unión entre posiciones 2 y 3)'],
            ['code' => 'LB24', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 4)'],
            ['code' => 'LB25', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 5)'],
            ['code' => 'LB26', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 2 y 6)'],
            ['code' => 'LB27', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 7)'],
            ['code' => 'LB28', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 8)'],
            ['code' => 'LB29', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 2 y 9)'],
            ['code' => 'LB34', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 3 y 4)'],
            ['code' => 'LB35', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 5)'],
            ['code' => 'LB36', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 3 y 6)'],
            ['code' => 'LB37', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 7)'],
            ['code' => 'LB38', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 8)'],
            ['code' => 'LB39', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 3 y 9)'],
            ['code' => 'LB45', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 4 y 5)'],
            ['code' => 'LB46', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 4 y 6)'],
            ['code' => 'LB47', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 4 y 7)'],
            ['code' => 'LB48', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 4 y 8)'],
            ['code' => 'LB49', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 4 y 9)'],
            ['code' => 'LB56', 'description' => 'Refuerzo transversal izquierdo (unión entre posiciones 5 y 6)'],
            ['code' => 'LB57', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 5 y 7)'],
            ['code' => 'LB58', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 5 y 8)'],
            ['code' => 'LB59', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 5 y 9)'],
            ['code' => 'LB67', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 6 y 7)'],
            ['code' => 'LB68', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 6 y 8)'],
            ['code' => 'LB69', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 6 y 9)'],
            ['code' => 'LB78', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 7 y 8)'],
            ['code' => 'LB79', 'description' => 'Refuerzo diagonal izquierdo (unión entre posiciones 7 y 9)'],
            ['code' => 'LB89', 'description' => 'Refuerzo longitudinal izquierdo (unión entre posiciones 8 y 9)'],
        ];

        $now = now();
        foreach (array_chunk($locations, 50) as $chunk) {
            foreach ($chunk as &$row) {
                $row['created_at'] = $now;
                $row['updated_at'] = $now;
            }
            DB::table('locations')->insert($chunk);
        }
    }
}
