<?php

namespace Database\Seeders;

use App\Models\ShippingLine;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ShippingLineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $shippingLines = [
            ['code' => 'MAEU', 'name' => 'Maersk Line'],
            ['code' => 'MSCU', 'name' => 'Mediterranean Shipping Company (MSC)'],
            ['code' => 'CMDU', 'name' => 'CMA CGM Group'],
            ['code' => 'COSU', 'name' => 'COSCO Shipping Lines'],
            ['code' => 'HLCU', 'name' => 'Hapag-Lloyd'],
            ['code' => 'EVEG', 'name' => 'Evergreen Marine'],
            ['code' => 'ONEY', 'name' => 'Ocean Network Express (ONE)'],
            ['code' => 'YMLU', 'name' => 'Yang Ming Marine Transport'],
            ['code' => 'HMMU', 'name' => 'Hyundai Merchant Marine (HMM)'],
            ['code' => 'ZIMU', 'name' => 'ZIM Integrated Shipping Services'],
            ['code' => 'WANH', 'name' => 'Wan Hai Lines'],
            ['code' => 'CSAV', 'name' => 'Compañía Sudamericana de Vapores (CSAV)'],
            ['code' => 'ALIA', 'name' => 'Aliança Navegação (Hapag-Lloyd Group)'],
            ['code' => 'MERC', 'name' => 'Mercosul Line'],
            ['code' => 'LATU', 'name' => 'Latam Lines'],
            ['code' => 'GRLA', 'name' => 'Grimaldi Lines'],
            ['code' => 'SEAL', 'name' => 'Sealand (Maersk)'],
            ['code' => 'NCLI', 'name' => 'Nordana Line'],
            ['code' => 'MMLP', 'name' => 'Marfret'],
            ['code' => 'SMFL', 'name' => 'Samskip'],
            ['code' => 'DALI', 'name' => 'Dalian Line'],
            ['code' => 'KMTL', 'name' => 'KMT Line'],
            ['code' => 'LCTC', 'name' => 'Log-In Logística Intermodal'],
            ['code' => 'CSPL', 'name' => 'China Shipping (COSCO)'],
            ['code' => 'CCNI', 'name' => 'Compañía Chilena de Navegación Interoceánica'],
            ['code' => 'NSSA', 'name' => 'Norsul Shipping Agency'],
            ['code' => 'ARCA', 'name' => 'Arca Shipping Lines'],
            ['code' => 'TRSC', 'name' => 'Transmares'],
            ['code' => 'SEAT', 'name' => 'Seatrade'],
            ['code' => 'HAMB', 'name' => 'Hamburg Süd'],
            ['code' => 'OOLU', 'name' => 'OOCL'],
            ['code' => 'NYKL', 'name' => 'NYK Line'],
            ['code' => 'KLEL', 'name' => 'K Line'],
            ['code' => 'MOLU', 'name' => 'MOL'],
            ['code' => 'SAFM', 'name' => 'Safmarine'],
            ['code' => 'UASC', 'name' => 'United Arab Shipping Company'],
            ['code' => 'APLU', 'name' => 'APL'],
            ['code' => 'CHSH', 'name' => 'Cheng Lie Navigation'],
            ['code' => 'CNCO', 'name' => 'CNC Line'],
            ['code' => 'EGLV', 'name' => 'ELG Shipping'],
            ['code' => 'EMCL', 'name' => 'Emirates Shipping Line'],
            ['code' => 'FESC', 'name' => 'Far Eastern Shipping Company'],
            ['code' => 'GOLD', 'name' => 'Gold Star Line'],
            ['code' => 'HEUN', 'name' => 'Heung-A Line'],
            ['code' => 'HSD', 'name' => 'HSD Line'],
            ['code' => 'IAL', 'name' => 'IAL Shipping'],
            ['code' => 'IRIS', 'name' => 'IRIS Lines'],
            ['code' => 'JST', 'name' => 'Jiangsu Tongtong Shipping'],
            ['code' => 'KANA', 'name' => 'Kanal Shipping'],
            ['code' => 'KLNE', 'name' => 'Korea Line'],
            ['code' => 'MATS', 'name' => 'Matson'],
            ['code' => 'MCC', 'name' => 'Merchant Container Carrier'],
            ['code' => 'MCPH', 'name' => 'McPhaukins Shipping'],
            ['code' => 'MITL', 'name' => 'Mitsui O.S.K. Lines'],
            ['code' => 'NALS', 'name' => 'NAL Lines'],
            ['code' => 'NCLU', 'name' => 'New China Line'],
            ['code' => 'NNSH', 'name' => 'Nannong Shipping'],
            ['code' => 'NSAL', 'name' => 'NileDutch Africa Line'],
            ['code' => 'PANO', 'name' => 'Pan Ocean'],
            ['code' => 'PCL', 'name' => 'PCL (Pacific Container Line)'],
            ['code' => 'PIL', 'name' => 'Pacific International Lines'],
            ['code' => 'RCL', 'name' => 'Regional Container Lines'],
            ['code' => 'RINA', 'name' => 'RINA Shipping'],
            ['code' => 'SALS', 'name' => 'Salam Pacific Lines'],
            ['code' => 'SCAN', 'name' => 'Scan Shipping'],
            ['code' => 'SITC', 'name' => 'SITC Container Lines'],
            ['code' => 'SJTS', 'name' => 'Sino-Japanese Transport'],
            ['code' => 'SMLI', 'name' => 'SM Line'],
            ['code' => 'SOCH', 'name' => 'Société Navale Caennaise'],
            ['code' => 'SPLI', 'name' => 'Spliethoff'],
            ['code' => 'STRA', 'name' => 'Strahlmann Lines'],
            ['code' => 'TSLI', 'name' => 'TS Lines'],
            ['code' => 'UCL', 'name' => 'Unifeeder'],
            ['code' => 'UESL', 'name' => 'Uni-Express Ship'],
            ['code' => 'WHLC', 'name' => 'Westwood Shipping Lines'],
            ['code' => 'XPRT', 'name' => 'X-Press Feeders'],
            ['code' => 'ZCO', 'name' => 'Zhonggu Shipping'],
            ['code' => 'ZOSC', 'name' => 'Zodiac Maritime'],
            ['code' => 'MARS', 'name' => 'Mariana Express Lines'],
            ['code' => 'TMM', 'name' => 'Transportación Marítima Mexicana'],
            ['code' => 'TMMC', 'name' => 'TMM Container Line'],
            ['code' => 'TPNM', 'name' => 'Tropical Shipping'],
            ['code' => 'VEGA', 'name' => 'Vega Reederei'],
            ['code' => 'VOLC', 'name' => 'Volcafe'],
            ['code' => 'WECL', 'name' => 'West Coast Line'],
            ['code' => 'WEWL', 'name' => 'Westwood Wilhelmsen'],
            ['code' => 'WSPL', 'name' => 'World Shipping Partners'],
            ['code' => 'YANG', 'name' => 'Yangzijiang Shipping'],
            ['code' => 'YMLI', 'name' => 'Yang Ming Line'],
            ['code' => 'ZELA', 'name' => 'Zela Shipping'],
            ['code' => 'ZEST', 'name' => 'Zest Shipping'],
            ['code' => 'DLMT', 'name' => 'Del Monte Shipping'],
            ['code' => 'CHQT', 'name' => 'Chiquita Brands International'],
            ['code' => 'STFR', 'name' => 'Star Fruit'],
            ['code' => 'FCFR', 'name' => 'FCF Reefer'],
            ['code' => 'FRUT', 'name' => 'Frutera Naviera'],
            ['code' => 'GREX', 'name' => 'Great White Fleet (Del Monte)'],
            ['code' => 'BANF', 'name' => 'Banana Fleet'],
            ['code' => 'DOLP', 'name' => 'Dole Ocean Cargo Express'],
            ['code' => 'NIRE', 'name' => 'Nire Reefer'],
            ['code' => 'SEAF', 'name' => 'Seafrigo'],
            ['code' => 'COOL', 'name' => 'Cool Carriers'],
            ['code' => 'BALT', 'name' => 'Baltic Reefers'],
            ['code' => 'ORCA', 'name' => 'Orca Lines'],
            ['code' => 'POLR', 'name' => 'Polar Reefer'],
            ['code' => 'AGRF', 'name' => 'Agrofert Shipping'],
        ];

        foreach ($shippingLines as $line) {
            ShippingLine::create($line);
        }
    }
}
